"""initial_schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-31 17:25:28.966508

Autogenerated from backend.models, then reviewed. Notes:
- The guide's required `campaign_leads(campaign_id)` index is discharged by the
  composite PK `(campaign_id, business_id)` — its leading column.
- Enum columns are VARCHAR(32) + CHECK (native_enum=False), not native PG ENUM.
- RLS enable/force + policies are 0003 (autogenerate is blind to them).
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('businesses',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_businesses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_businesses')),
    sa.UniqueConstraint('id', 'user_id', name='uq_businesses_id_user_id')
    )
    op.create_index(op.f('ix_businesses_user_id'), 'businesses', ['user_id'], unique=False)
    op.create_index('ix_businesses_user_normalized_name', 'businesses', ['user_id', 'normalized_name'], unique=False)
    op.create_index('uq_businesses_user_domain', 'businesses', ['user_id', 'domain'], unique=True, postgresql_where=sa.text('domain IS NOT NULL'))
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('industries', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('budget_min', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'running', 'complete', 'failed', name='campaignstatus', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_campaigns_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('id', 'user_id', name='uq_campaigns_id_user_id')
    )
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('services', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('target_industries', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('target_locations', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('price_range_min', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('price_range_max', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('icp_notes', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_profiles'))
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('agent', sa.Enum('discovery', 'research', 'audit', 'opportunity', 'outreach', name='agentname', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='runstatus', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('business_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id', 'user_id'], ['campaigns.id', 'campaigns.user_id'], name='fk_agent_runs_campaign', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs')),
    sa.UniqueConstraint('id', 'user_id', name='uq_agent_runs_id_user_id')
    )
    op.create_index('ix_agent_runs_campaign_started', 'agent_runs', ['campaign_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_table('business_contacts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('phone', 'email', 'facebook', 'instagram', 'website', 'other', name='contacttype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_business_contacts_confidence_range')),
    sa.ForeignKeyConstraint(['business_id', 'user_id'], ['businesses.id', 'businesses.user_id'], name='fk_business_contacts_business', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_contacts'))
    )
    op.create_index('ix_business_contacts_business_id', 'business_contacts', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_contacts_user_id'), 'business_contacts', ['user_id'], unique=False)
    op.create_table('business_evidence',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('observed_value', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.Enum('gap', 'strength', name='evidencekind', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('factor', sa.Enum('no_website', 'broken_website', 'outdated_website', 'no_booking', 'no_ordering', 'active_social', 'high_review_count', 'contactable', 'industry_match', 'location_match', name='scorefactor', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_business_evidence_confidence_range')),
    sa.ForeignKeyConstraint(['business_id', 'user_id'], ['businesses.id', 'businesses.user_id'], name='fk_business_evidence_business', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_evidence'))
    )
    op.create_index('ix_business_evidence_business_id', 'business_evidence', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_evidence_user_id'), 'business_evidence', ['user_id'], unique=False)
    op.create_table('business_sources',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id', 'user_id'], ['businesses.id', 'businesses.user_id'], name='fk_business_sources_business', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_sources'))
    )
    op.create_index('ix_business_sources_business_id', 'business_sources', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_sources_user_id'), 'business_sources', ['user_id'], unique=False)
    op.create_table('campaign_leads',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'replied', 'meeting', 'proposal', 'won', 'lost', name='leadstatus', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'new'"), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id', 'user_id'], ['businesses.id', 'businesses.user_id'], name='fk_campaign_leads_business', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id', 'user_id'], ['campaigns.id', 'campaigns.user_id'], name='fk_campaign_leads_campaign', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'business_id', name=op.f('pk_campaign_leads'))
    )
    op.create_index('ix_campaign_leads_business_id', 'campaign_leads', ['business_id'], unique=False)
    op.create_index(op.f('ix_campaign_leads_user_id'), 'campaign_leads', ['user_id'], unique=False)
    op.create_table('digital_audits',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('has_website', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('website_status', sa.Enum('none', 'broken', 'outdated', 'basic', 'good', name='websitestatus', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'none'"), nullable=False),
    sa.Column('has_booking', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_ordering', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mobile_friendly', sa.Boolean(), nullable=True),
    sa.Column('social_presence', sa.Enum('none', 'inactive', 'active', 'very_active', name='socialpresence', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'none'"), nullable=False),
    sa.Column('digital_gaps', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('audited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_digital_audits_confidence_range')),
    sa.ForeignKeyConstraint(['business_id', 'user_id'], ['businesses.id', 'businesses.user_id'], name='fk_digital_audits_business', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id', name=op.f('pk_digital_audits'))
    )
    op.create_index(op.f('ix_digital_audits_user_id'), 'digital_audits', ['user_id'], unique=False)
    op.create_table('lead_activity',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('discovery', 'evidence', 'reply', 'qualified', 'campaign', name='activitykind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('note', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id', 'user_id'], ['businesses.id', 'businesses.user_id'], name='fk_lead_activity_business', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lead_activity_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_activity'))
    )
    op.create_index(op.f('ix_lead_activity_user_id'), 'lead_activity', ['user_id'], unique=False)
    op.create_table('lead_opportunities',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_service', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('sales_angle', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('reasoning', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_lead_opportunities_confidence_range')),
    sa.ForeignKeyConstraint(['business_id', 'user_id'], ['businesses.id', 'businesses.user_id'], name='fk_lead_opportunities_business', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id', name=op.f('pk_lead_opportunities'))
    )
    op.create_index(op.f('ix_lead_opportunities_user_id'), 'lead_opportunities', ['user_id'], unique=False)
    op.create_table('lead_scores',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('model_version', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0', name=op.f('ck_lead_scores_score_nonneg')),
    sa.ForeignKeyConstraint(['business_id', 'user_id'], ['businesses.id', 'businesses.user_id'], name='fk_lead_scores_business', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id', 'user_id'], ['campaigns.id', 'campaigns.user_id'], name='fk_lead_scores_campaign', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id', 'campaign_id', name=op.f('pk_lead_scores'))
    )
    op.create_index('ix_lead_scores_campaign_score', 'lead_scores', ['campaign_id', sa.literal_column('score DESC')], unique=False)
    op.create_index(op.f('ix_lead_scores_user_id'), 'lead_scores', ['user_id'], unique=False)
    op.create_table('outreach_messages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'facebook_dm', name='outreachchannel', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('draft', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'replied', 'bounced', name='outreachstatus', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edited_by_user', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id', 'user_id'], ['businesses.id', 'businesses.user_id'], name='fk_outreach_messages_business', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outreach_messages'))
    )
    op.create_index('ix_outreach_messages_business_id', 'outreach_messages', ['business_id'], unique=False)
    op.create_index(op.f('ix_outreach_messages_user_id'), 'outreach_messages', ['user_id'], unique=False)
    op.create_table('agent_errors',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('error_type', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'user_id'], ['agent_runs.id', 'agent_runs.user_id'], name='fk_agent_errors_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_errors'))
    )
    op.create_index('ix_agent_errors_run_id', 'agent_errors', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_errors_user_id'), 'agent_errors', ['user_id'], unique=False)
    op.create_table('agent_tool_calls',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('tool', sa.Text(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ms', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'user_id'], ['agent_runs.id', 'agent_runs.user_id'], name='fk_agent_tool_calls_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_tool_calls'))
    )
    op.create_index('ix_agent_tool_calls_run_id', 'agent_tool_calls', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_user_id'), 'agent_tool_calls', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_tool_calls_user_id'), table_name='agent_tool_calls')
    op.drop_index('ix_agent_tool_calls_run_id', table_name='agent_tool_calls')
    op.drop_table('agent_tool_calls')
    op.drop_index(op.f('ix_agent_errors_user_id'), table_name='agent_errors')
    op.drop_index('ix_agent_errors_run_id', table_name='agent_errors')
    op.drop_table('agent_errors')
    op.drop_index(op.f('ix_outreach_messages_user_id'), table_name='outreach_messages')
    op.drop_index('ix_outreach_messages_business_id', table_name='outreach_messages')
    op.drop_table('outreach_messages')
    op.drop_index(op.f('ix_lead_scores_user_id'), table_name='lead_scores')
    op.drop_index('ix_lead_scores_campaign_score', table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_lead_opportunities_user_id'), table_name='lead_opportunities')
    op.drop_table('lead_opportunities')
    op.drop_index(op.f('ix_lead_activity_user_id'), table_name='lead_activity')
    op.drop_table('lead_activity')
    op.drop_index(op.f('ix_digital_audits_user_id'), table_name='digital_audits')
    op.drop_table('digital_audits')
    op.drop_index(op.f('ix_campaign_leads_user_id'), table_name='campaign_leads')
    op.drop_index('ix_campaign_leads_business_id', table_name='campaign_leads')
    op.drop_table('campaign_leads')
    op.drop_index(op.f('ix_business_sources_user_id'), table_name='business_sources')
    op.drop_index('ix_business_sources_business_id', table_name='business_sources')
    op.drop_table('business_sources')
    op.drop_index(op.f('ix_business_evidence_user_id'), table_name='business_evidence')
    op.drop_index('ix_business_evidence_business_id', table_name='business_evidence')
    op.drop_table('business_evidence')
    op.drop_index(op.f('ix_business_contacts_user_id'), table_name='business_contacts')
    op.drop_index('ix_business_contacts_business_id', table_name='business_contacts')
    op.drop_table('business_contacts')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_campaign_started', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('uq_businesses_user_domain', table_name='businesses', postgresql_where=sa.text('domain IS NOT NULL'))
    op.drop_index('ix_businesses_user_normalized_name', table_name='businesses')
    op.drop_index(op.f('ix_businesses_user_id'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_table('users')
    # ### end Alembic commands ###
